// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShjWSNLwVOiaGh34ei7NlVe2uXSC8g2E',
    appId: '1:245416282683:web:54dfc1ac47dcd5406caa1e',
    messagingSenderId: '245416282683',
    projectId: 'focus-a5e5c',
    authDomain: 'focus-a5e5c.firebaseapp.com',
    storageBucket: 'focus-a5e5c.firebasestorage.app',
    measurementId: 'G-8GJDKGNPD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fJP5kGa_SlVtJ3cZDQ0nCK5zk5bAWaI',
    appId: '1:245416282683:android:a66c5bbfeffb4d9b6caa1e',
    messagingSenderId: '245416282683',
    projectId: 'focus-a5e5c',
    storageBucket: 'focus-a5e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaruOJN0JCS5Jq11OLhTB3dwmW9BxUp4c',
    appId: '1:245416282683:ios:8a63672992182a7a6caa1e',
    messagingSenderId: '245416282683',
    projectId: 'focus-a5e5c',
    storageBucket: 'focus-a5e5c.firebasestorage.app',
    iosBundleId: 'com.example.focusflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaruOJN0JCS5Jq11OLhTB3dwmW9BxUp4c',
    appId: '1:245416282683:ios:8a63672992182a7a6caa1e',
    messagingSenderId: '245416282683',
    projectId: 'focus-a5e5c',
    storageBucket: 'focus-a5e5c.firebasestorage.app',
    iosBundleId: 'com.example.focusflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShjWSNLwVOiaGh34ei7NlVe2uXSC8g2E',
    appId: '1:245416282683:web:c944651d9f19abdc6caa1e',
    messagingSenderId: '245416282683',
    projectId: 'focus-a5e5c',
    authDomain: 'focus-a5e5c.firebaseapp.com',
    storageBucket: 'focus-a5e5c.firebasestorage.app',
    measurementId: 'G-M61822ELW5',
  );
}
